<a href="https://colab.research.google.com/github/Leonanda1013/DataLoverz/blob/main/Pytorch/2_pytorch_tensorOperator_reshape%26slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

Reshape = ubah “bentuk wadah” <br>
view() → mirip reshape (tapi butuh memory contiguous) <br>
.flatten() → langsung jadi 1D <br>
Slice = ambil “isi sebagian”

In [4]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Reshape & view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [12]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch3[1] = 4321
my_torch3

tensor([[   0,    1,    2,    3,    4],
        [4321, 4321, 4321, 4321, 4321]])

In [15]:
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch4[1] = 1234
my_torch4

tensor([   0, 1234,    2,    3,    4,    5,    6,    7,    8,    9])

In [17]:
#Slice
my_torch5 = torch.arange(10)
my_torch5 = my_torch5.reshape(5,2)
print(my_torch5)
print(my_torch5[:,0])
print(my_torch5[:,1])
print(my_torch5[:,1:])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([0, 2, 4, 6, 8])
tensor([1, 3, 5, 7, 9])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])
