<a href="https://colab.research.google.com/github/Leonanda1013/DataLoverz/blob/main/Pytorch/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

Jadi tensors itu sama seperti wadah data, sama seperti array di numpy, namun bedanya kalo numpy dia ngga bisa jalan pakai gpu sedangkan tensor bisa karena berasal dari pytorch


In [7]:
# Array List
list = [1,2,3,4]
print(list)

list_2D = [[1,2,3,4],[5,6,7,8]]
print(list_2D)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [8]:
# Array Numpy
array = np.array(list)
print(array)

[1 2 3 4]


In [9]:
# Tesors
tensor_2D = torch.randn(2,2)
print(tensor_2D)

tensor([[-0.5475, -2.2794],
        [-0.3286, -2.4998]])


In [10]:
tensor_3D = torch.randn(2,3,4)
tensor_3D

tensor([[[ 1.6428,  0.8279,  0.8148,  0.3298],
         [-0.6952,  1.0425,  0.4147, -0.5589],
         [ 1.8305, -1.1532,  1.1991, -0.4072]],

        [[-0.3415, -0.4317, -0.9972, -2.1192],
         [-0.2309,  0.3208,  0.2871,  0.9376],
         [-1.8589,  0.5919,  0.2917,  0.1612]]])

In [12]:
# membuat tensors dari numpy array
t_np = torch.tensor(array)
t_np

tensor([1, 2, 3, 4])